### ISSUE TITLE
Error when I am running train.py, any ideas ? 

### ISSUE THREAD

**Issue by thug1705** [synckey/tensorflow_lstm_ctc_ocr#11]
Traceback (most recent call last):
  File "/train.py", line 133, in <module>
    train()
  File "/train.py", line 109, in train
    (batch + 1) * common.BATCH_SIZE)
  File "\utils.py", line 79, in get_data_set
    inputs, codes = common.unzip(list(common.read_data_for_lstm_ctc(dirname, start_index, end_index)))
  File "\common.py", line 113, in read_data_for_lstm_ctc
    if not data_set in dirname:
TypeError: 'in <string>' requires string as left operand, not dict

**Comment by synckey** [comment]
please run gen.py before you run train.
