### ISSUE TITLE
error in running detect.py

### ISSUE THREAD

**Issue by engahmed1190** [synckey/tensorflow_lstm_ctc_ocr#20]
Hi @synckey 

I have an error will running the detect file , looks like error related about initializing variable in the model 

```
loading small_test
(256, 64)
2018-01-09 22:47:05.379140: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2018-01-09 22:47:05.379441: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-09 22:47:05.380618: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-09 22:47:05.382781: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-09 22:47:05.383239: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-09 22:47:05.383682: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Restore from models\ocr.model-103000
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
  File "C:\Anaconda3\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Variable_4
         [[Node: Variable_4/read = Identity[T=DT_FLOAT, _class=["loc:@Variable_4"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_4)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detect.py", line 62, in <module>
    print(detect(test_inputs, test_targets, test_seq_len))
  File "detect.py", line 32, in detect
    dd = sess.run(decoded[0], feed_dict=feed_dict)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Variable_4
         [[Node: Variable_4/read = Identity[T=DT_FLOAT, _class=["loc:@Variable_4"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_4)]]

Caused by op 'Variable_4/read', defined at:
  File "detect.py", line 62, in <module>
    print(detect(test_inputs, test_targets, test_seq_len))
  File "detect.py", line 19, in detect
    logits, inputs, targets, seq_len, W, b = model.get_train_model()
  File "C:\Desktop\Text_Detector\tensorflow_lstm_ctc_ocr\model.py", line 83, in get_train_model
    inputs, features = convolutional_layers()
  File "C:\Desktop\Text_Detector\tensorflow_lstm_ctc_ocr\model.py", line 58, in convolutional_layers
    W_conv3 = weight_variable([5, 5, 64, 128])
  File "C:\Desktop\Text_Detector\tensorflow_lstm_ctc_ocr\model.py", line 13, in weight_variable
    return tf.Variable(initial)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 200, in __init__
    expected_shape=expected_shape)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 319, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1303, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Variable_4
         [[Node: Variable_4/read = Identity[T=DT_FLOAT, _class=["loc:@Variable_4"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_4)]]
```
Any Help

**Comment by synckey** [comment]
I would push the new code to see if it works for you.

发自我的 iPhone

**Comment by jihadbourassi** [comment]
@engahmed1190  How did you run detect.py? i don't know how the command is parsed

**Comment by engahmed1190** [comment]
It's related to version difference in tensorflow

**Comment by jihadbourassi** [comment]
@engahmed1190 Could you provide me with the command line you wrote for detect.py?
