### ISSUE TITLE
程序使用

### ISSUE THREAD

**Issue by anxingle** [synckey/tensorflow_lstm_ctc_ocr#4]
您好，请问您这个代码是使用gen.py来生成验证码，然后在使用lstm_and_ctc_ocr_train.py来训练吗？ 我运行gen.py 出错。
 libdc1394 error: Failed to initialize libdc1394
 12
 Traceback (most recent call last):
 File "gen.py", line 293, in <module>
   for img_idx, (im, c, p) in enumerate(im_gen):
    File "gen.py", line 283, in generate_ims
       yield generate_im(random.choice(char_ims), num_bg_images)
     File "gen.py", line 243, in generate_im
       bg = generate_bg(num_bg_images)
    File "gen.py", line 228, in generate_bg
      fname = "bgs/{:08d}.jpg".format(random.randint(0, num_bg_images - 1))
    File "/usr/lib/python2.7/random.py", line 240, in randint
      return self.randrange(a, b+1)
    File "/usr/lib/python2.7/random.py", line 216, in randrange
      raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
  ValueError: empty range for randrange() (0,-2, -2)
这个bgs目录如何使用呢？   可不可以在readme.md中加入一些使用须知....谢谢您。

**Comment by synckey** [comment]
你好，我已经在 readme中加入使用说明，并且迁移到 tensorflow 1.0了，不好意思，好久没上 github，回复太晚了。

**Comment by wellhao** [comment]
你好 ，我在虚拟机上运行你的代码，在训练的时候出现 str = common.DIGITS[spars_tensor[1][m]]
IndexError: string index out of range，我使用的也是tf1.0，不知道问题在哪里。

**Comment by synckey** [comment]
能把栈全贴出来么？

**Comment by wellhao** [comment]
Traceback (most recent call last):
  File "lstm_and_ctc_ocr_train.py", line 132, in <module>
    train()
  File "lstm_and_ctc_ocr_train.py", line 112, in train
    c, steps = do_batch()
  File "lstm_and_ctc_ocr_train.py", line 90, in do_batch
    do_report()
  File "lstm_and_ctc_ocr_train.py", line 83, in do_report
    report_accuracy(dd, test_targets)
  File "lstm_and_ctc_ocr_train.py", line 35, in report_accuracy
    original_list = decode_sparse_tensor(test_targets)
  File "/mnt/hgfs/share/tensorflow_lstm_ctc_ocr-master/tensorflow_lstm_ctc_ocr-master/utils.py", line 128, in decode_sparse_tensor
    result.append(decode_a_seq(index, sparse_tensor))
  File "/mnt/hgfs/share/tensorflow_lstm_ctc_ocr-master/tensorflow_lstm_ctc_ocr-master/utils.py", line 101, in decode_a_seq
    str = common.DIGITS[spars_tensor[1][m]]
IndexError: string index out of range
 谢谢啦

**Comment by wellhao** [comment]
@synckey  最开始我是随便弄了几张图做背景，训练报错，后来下了你使用数据还是出错，不知道是不是tensorflow的问题，我使用的是1.0的版本。windows和虚拟机里面的错误都一样

**Comment by synckey** [comment]
@wellhao 看不出来错误，能把代码地址给一下么？

**Comment by wellhao** [comment]
@synckey 代码用的就是你的代码，python的版本是3.5.2  tensorflow直接用pip装的tensorflow_gpu-1.0.0-cp35-cp35m-win_amd64.whl ，虚拟机下的是cpu版本  机器是win10+cuda8.0 。谢谢!你的邮箱synckey@gmail.com是常用邮箱吧

**Comment by synckey** [comment]
@wellhao 你试试 Python2.7，我只在2.7下面测试过。

**Comment by ilovin** [comment]
同样的错误，把**spars_tensor[1][m]** 打印出来，发现是10
然而DIGITS是0-9，所以报错，不知道这块写得是不是有问题，没加空格？
